import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CONFIG_FILE } from './init.js';
import { exists, readJson, resolveInside } from '../project.js';

export const DEFAULT_TOKENS_FILE = 'src/styles/sillar.tokens.css';
const requiredColors = ['brand', 'brand-hover', 'brand-contrast', 'brand-soft', 'brand-soft-border'];

function parseHex(value) {
  const match = /^#([\da-f]{3}|[\da-f]{6})$/i.exec(value ?? '');
  if (!match) throw new Error(`Invalid brand color: ${value}. Use a hex color such as #0f766e.`);
  const expanded = match[1].length === 3 ? [...match[1]].map((part) => part + part).join('') : match[1];
  return [0, 2, 4].map((offset) => Number.parseInt(expanded.slice(offset, offset + 2), 16));
}

function toHex(rgb) { return `#${rgb.map((channel) => Math.round(channel).toString(16).padStart(2, '0')).join('')}`; }
function mix(color, target, amount) { return toHex(color.map((channel, index) => channel + (target[index] - channel) * amount)); }
function luminance(rgb) { const values = rgb.map((channel) => { const value = channel / 255; return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4; }); return values[0] * 0.2126 + values[1] * 0.7152 + values[2] * 0.0722; }
export function contrastRatio(first, second) { const values = [luminance(parseHex(first)), luminance(parseHex(second))].sort((a, b) => b - a); return (values[0] + 0.05) / (values[1] + 0.05); }
function contrastColor(color) { return contrastRatio(color, '#ffffff') >= contrastRatio(color, '#071019') ? '#ffffff' : '#071019'; }
function rgba(rgb, alpha) { return `rgba(${rgb.join(', ')}, ${alpha})`; }

export function createTokenTheme(brand = '#0f766e') {
  const light = parseHex(brand);
  const dark = parseHex(mix(light, [255, 255, 255], 0.48));
  const lightBrand = toHex(light);
  const darkBrand = toHex(dark);
  return `/* Generated by Sillar CLI. Import after sillar-ui/styles.css. */
:root {
  --slr-color-brand: ${lightBrand};
  --slr-color-brand-hover: ${mix(light, [0, 0, 0], 0.18)};
  --slr-color-brand-contrast: ${contrastColor(lightBrand)};
  --slr-color-brand-soft: ${mix(light, [255, 255, 255], 0.9)};
  --slr-color-brand-soft-border: ${mix(light, [255, 255, 255], 0.62)};
  --slr-shadow-focus: 0 0 0 3px ${rgba(light, 0.22)};
}

:is(.dark, [data-theme="dark"]) {
  --slr-color-brand: ${darkBrand};
  --slr-color-brand-hover: ${mix(dark, [255, 255, 255], 0.2)};
  --slr-color-brand-contrast: ${contrastColor(darkBrand)};
  --slr-color-brand-soft: ${mix(light, [7, 16, 25], 0.68)};
  --slr-color-brand-soft-border: ${mix(light, [7, 16, 25], 0.4)};
  --slr-shadow-focus: 0 0 0 3px ${rgba(dark, 0.26)};
}
`;
}

function declarations(block) { return Object.fromEntries([...block.matchAll(/--slr-color-([\w-]+)\s*:\s*([^;]+);/g)].map((match) => [match[1], match[2].trim()])); }

export function inspectTokenTheme(source) {
  const blocks = { light: /:root\s*{([^}]*)}/s.exec(source)?.[1] ?? '', dark: /:is\(\.dark,\s*\[data-theme=["']dark["']\]\)\s*{([^}]*)}/s.exec(source)?.[1] ?? '' };
  const result = { light: declarations(blocks.light), dark: declarations(blocks.dark) };
  const errors = [];
  for (const mode of ['light', 'dark']) {
    for (const token of requiredColors) if (!result[mode][token]) errors.push(`${mode}: missing --slr-color-${token}`);
    if (!/--slr-shadow-focus\s*:/.test(blocks[mode])) errors.push(`${mode}: missing --slr-shadow-focus`);
    if (result[mode].brand && result[mode]['brand-contrast']) {
      try { const ratio = contrastRatio(result[mode].brand, result[mode]['brand-contrast']); if (ratio < 4.5) errors.push(`${mode}: brand contrast ${ratio.toFixed(2)}:1 is below 4.5:1`); }
      catch { errors.push(`${mode}: brand and contrast tokens must use hex colors`); }
    }
  }
  return { valid: errors.length === 0, errors, ...result };
}

async function tokenPath(cwd) { const config = await readJson(path.join(cwd, CONFIG_FILE)); return resolveInside(cwd, config?.tokensFile || DEFAULT_TOKENS_FILE); }

export async function initTokens({ cwd, brand, force = false, output = console.log }) {
  const target = await tokenPath(cwd);
  await mkdir(path.dirname(target), { recursive: true });
  try { await writeFile(target, createTokenTheme(brand), { flag: force ? 'w' : 'wx' }); }
  catch (error) { if (error?.code === 'EEXIST') throw new Error(`${path.relative(cwd, target)} already exists. Use --force to replace it.`); throw error; }
  output(`Created ${path.relative(cwd, target)}`);
  output(`Import "./${path.basename(target)}" after "sillar-ui/styles.css".`);
  return target;
}

export async function checkTokens({ cwd, output = console.log }) {
  const target = await tokenPath(cwd);
  if (!(await exists(target))) throw new Error(`${path.relative(cwd, target)} not found. Run "sillar tokens init" first.`);
  const result = inspectTokenTheme(await readFile(target, 'utf8'));
  if (!result.valid) throw new Error(`Token validation failed:\n${result.errors.map((error) => `- ${error}`).join('\n')}`);
  output(`✓ ${path.relative(cwd, target)}: light and dark token contracts are complete.`);
  output('✓ Brand foreground contrast meets WCAG AA (4.5:1).');
  return result;
}
