import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';

export default defineConfig({
  plugins: [react()],
  build: {
    lib: {
      entry: {
        index: 'src/index.ts',
        accordion: 'src/accordion.tsx',
        a11y: 'src/a11y.tsx',
        badge: 'src/badge.tsx',
        button: 'src/button.tsx',
        'calculator-shell': 'src/calculator-shell.tsx',
        callout: 'src/callout.tsx',
        card: 'src/card.tsx',
        choice: 'src/choice.tsx',
        collapsible: 'src/collapsible.tsx',
        combobox: 'src/combobox.tsx',
        'confirm-dialog': 'src/confirm-dialog.tsx',
        'date-picker': 'src/date-picker.tsx',
        dialog: 'src/dialog.tsx',
        'dropdown-menu': 'src/dropdown-menu.tsx',
        'empty-state': 'src/empty-state.tsx',
        'export-actions': 'src/export-actions.tsx',
        field: 'src/field.tsx',
        'form-grid': 'src/form-grid.tsx',
        form: 'src/form.tsx',
        'icon-button': 'src/icon-button.tsx',
        input: 'src/input.tsx',
        label: 'src/label.tsx',
        'money-input': 'src/money-input.tsx',
        'navigation-menu': 'src/navigation-menu.tsx',
        popover: 'src/popover.tsx',
        progress: 'src/progress.tsx',
        'result-summary': 'src/result-summary.tsx',
        section: 'src/section.tsx',
        select: 'src/select.tsx',
        'select-root': 'src/select-root.tsx',
        separator: 'src/separator.tsx',
        slot: 'src/slot.tsx',
        switch: 'src/switch.tsx',
        tabs: 'src/tabs.tsx',
        'text-field': 'src/text-field.tsx',
        textarea: 'src/textarea.tsx',
        toast: 'src/toast.tsx',
        tooltip: 'src/tooltip.tsx',
        utils: 'src/utils.ts',
      },
      formats: ['es'],
      fileName: (_format, entryName) => `${entryName}.js`,
      cssFileName: 'styles',
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        'react/jsx-runtime',
        'class-variance-authority',
        'clsx',
        'tailwind-merge',
      ],
    },
    sourcemap: true,
    emptyOutDir: true,
  },
});
