export const registry = {
  accordion: { entry: 'accordion', exports: ['Accordion', 'AccordionContent', 'AccordionItem', 'AccordionTrigger'] },
  badge: { entry: 'badge', exports: ['Badge'] },
  button: { entry: 'button', exports: ['Button'] },
  callout: { entry: 'callout', exports: ['Callout', 'CalloutDescription', 'CalloutIcon', 'CalloutTitle'] },
  card: { entry: 'card', exports: ['Card', 'CardAction', 'CardContent', 'CardDescription', 'CardFooter', 'CardHeader', 'CardTitle'] },
  checkbox: { entry: 'choice', exports: ['Checkbox'] },
  combobox: { entry: 'combobox', exports: ['Combobox'] },
  collapsible: { entry: 'collapsible', exports: ['Collapsible', 'CollapsibleContent', 'CollapsibleTrigger'] },
  'date-picker': { entry: 'date-picker', exports: ['DatePicker'] },
  dialog: { entry: 'dialog', exports: ['Dialog', 'DialogClose', 'DialogContent', 'DialogDescription', 'DialogFooter', 'DialogHeader', 'DialogOverlay', 'DialogPortal', 'DialogTitle', 'DialogTrigger'] },
  'dropdown-menu': { entry: 'dropdown-menu', exports: ['DropdownMenu', 'DropdownMenuContent', 'DropdownMenuGroup', 'DropdownMenuItem', 'DropdownMenuLabel', 'DropdownMenuPortal', 'DropdownMenuSeparator', 'DropdownMenuTrigger'] },
  field: { entry: 'field', exports: ['Field', 'FieldDescription', 'FieldError', 'FieldLabel'] },
  form: { entry: 'form', exports: ['Form', 'FormControl', 'FormDescription', 'FormItem', 'FormLabel', 'FormMessage', 'useForm'] },
  input: { entry: 'input', exports: ['Input'] },
  'navigation-menu': { entry: 'navigation-menu', exports: ['NavigationMenu', 'NavigationMenuContent', 'NavigationMenuItem', 'NavigationMenuLink', 'NavigationMenuList', 'NavigationMenuTrigger'] },
  popover: { entry: 'popover', exports: ['Popover', 'PopoverClose', 'PopoverContent', 'PopoverTrigger'] },
  progress: { entry: 'progress', exports: ['Progress', 'Skeleton'] },
  'radio-group': { entry: 'choice', exports: ['RadioGroup', 'RadioGroupItem'] },
  select: { entry: 'select-root', exports: ['SelectContent', 'SelectGroup', 'SelectItem', 'SelectLabel', 'SelectRoot', 'SelectSeparator', 'SelectTrigger', 'SelectValue'] },
  separator: { entry: 'separator', exports: ['Separator'] },
  switch: { entry: 'switch', exports: ['Switch'] },
  tabs: { entry: 'tabs', exports: ['Tabs', 'TabsContent', 'TabsList', 'TabsTrigger'] },
  textarea: { entry: 'textarea', exports: ['Textarea'] },
  toast: { entry: 'toast', exports: ['ToastProvider', 'ToastViewport', 'useToast'] },
  tooltip: { entry: 'tooltip', exports: ['Tooltip', 'TooltipContent', 'TooltipTrigger'] },
};

export const componentNames = Object.freeze(Object.keys(registry).sort());
